### ISSUE TITLE
Create Kanban Board for the React-redux group project

### ISSUE THREAD

**Issue by d4nQw3rty** [d4nQw3rty/space-travelers-hub#61]
https://github.com/users/d4nQw3rty/projects/1/views/1
This project has 3 team members

**Comment by prolajumokeoni** [comment]
Hi @Team
Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights
✔️ Good project board setup



## Required Changes ♻️

- [ ] Kindly make sure that your cards equal 24 as a team of 3 you are missing four cards, please check the [template](https://github.com/microverseinc/curriculum-react-redux/projects/1) and add the missing cards 👍🏿 

_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- N/A
Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification @prolajumokeoni.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by OscarFMdev** [comment]
Thank you very much @prolajumokeoni ! We are working on it, and also, thanks for the help through slack 🙌🏽

**Comment by OscarFMdev** [comment]
Thank you very much @brytebee ! 😄
